// NextJS
import Head from "next/head";
import Image from "next/image";
// Styles
import home from "../styles/Home.module.scss";
import destinations from "../styles/Destinations.module.scss";
import post from "../styles/Post.module.scss";

// SVG
import Earth from "../src/svg/Earth.svg";
import Mars from "../src/svg/Mars.svg";
import Jupiter from "../src/svg/Jupiter.svg";
import Comet from "../public/astronaut.png";

// Components
import Layout from "../components/layout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>PlanetX | Welcome to The Space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/planet.ico" />
      </Head>

      {/* Landing page */}
      <div className={home.main}>
        <div className={home["left-container"]}>
          <h1>
            <span>Welcome</span>
            <span>to The</span>
            <span className={home.gradient}>Space</span>
          </h1>
          <button>Explore topics</button>
        </div>
        <div className={home["right-container"]}>
          <Earth className={home.earth} />
        </div>
      </div>

      {/* Destinations */}
      <div className={destinations.main}>
        <h1 className={destinations.title}>Destinations</h1>

        <div className={destinations.topics}>
          <div className={destinations.topic}>
            <Mars className={destinations.svg} />
            <div className={destinations.title2}>Mars</div>
            <div className={destinations.desc}>
              Planet Mars, new images and discoveries, new information about survival there
            </div>
          </div>
          <div className={destinations.topic}>
            <Earth className={destinations.svg} />
            <div className={destinations.title2}>Earth</div>
            <div className={destinations.desc}>
              Planet Earth, the latest news and discoveries, new threats and new problems
            </div>
          </div>
          <div className={destinations.topic}>
            <Jupiter className={destinations.svg} />
            <div className={destinations.title2}>Jupiter</div>
            <div className={destinations.desc}>
              Planet Jupiter, images, composition and why it deserves to be analyzed better
            </div>
          </div>
        </div>
      </div>

      {/* Blog posts */}
      <div className={post.main}>
        <div className={post.title}>Recent published</div>
        <div className={post.carousel}>
          <div className={post.post}>
            <div className={post.imageContainer}>
              <Image src={Comet} alt="Post image" objectFit="cover" width="400" height="256" className={post.img} />
            </div>
            <div className={post.text}>
              <div className={post["post-title"]}>
                <span>Title</span>
              </div>
              <p className={`${post.desc} ${post.overflow}`}>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quae iste veniam eveniet incidunt esse,
                necessitatibus consectetur nihil quos. Qui, itaque, rem voluptatum quasi ab nemo aperiam, fugiat eius
                dolor nesciunt dolores minus laborum possimus totam repudiandae minima. Quasi rem dolorem sapiente
                dolores maxime sequi dolorum nihil, voluptates dolor, numquam suscipit corrupti iure? Id, nam assumenda!
                Quod voluptate, sequi veniam architecto perspiciatis nam odio necessitatibus exercitationem amet a ipsum
                ducimus ad? Eius alias quibusdam aliquam delectus? Necessitatibus perspiciatis, eveniet provident neque
                at voluptas dicta distinctio, placeat incidunt tenetur debitis. Eveniet ipsum temporibus quas omnis
                dolores aliquam optio a rem ipsam dolorum!
              </p>
              <a className={post.link} href="#">
                Read more
              </a>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}
