// NextJS
import Head from "next/head";
import Image from "next/image";

// React
import { useState, useEffect } from "react";

// Next themes
import { useTheme } from "next-themes";

// Styles
import hamburger from "../styles/Hamburger.module.scss";
import navigation from "../styles/Navigation.module.scss";
import home from "../styles/Home.module.css";
import toggle from "../styles/Switch.module.scss";

// Icons
import { IoPlanet } from "react-icons/io5";

// Components
import Layout from "../components/layout";

export default function Home() {
  const [hamburgerActive, setHamburgerActive] = useState(false);
  const [hiddenNav, setHiddenNav] = useState(false);

  const { theme, setTheme } = useTheme();

  useEffect(() => {
    let lastScrollY = window.scrollY;

    const onScroll = () => {
      if (window && lastScrollY < window.scrollY) setHiddenNav(true);
      else setHiddenNav(false);

      lastScrollY = window.scrollY;
    };

    window.removeEventListener("scroll", onScroll);
    window.addEventListener("scroll", onScroll, { passive: true });

    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  return (
    <Layout>
      <Head>
        <title>PlanetX | Welcome to The Space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/planet.ico" />
      </Head>

      {/* Navigation */}
      <div className={`${navigation.nav} ${hiddenNav && navigation.hidden}`}>
        {/* Logo */}
        <div className={navigation.logo}>
          <IoPlanet />
          <span>PlanetX</span>
        </div>

        <div className={navigation.btns}>
          {/* Theme toggler */}
          <label className={toggle.switch}>
            <input
              type="checkbox"
              onClick={() => {
                if (theme === "dark") setTheme("light");
                else setTheme("dark");
              }}
              defaultChecked={theme === "dark"}
            />
            <span className={toggle.slider}></span>
          </label>

          {/* Hamburger menu */}
          <button
            className={`${hamburger.hamburger} ${hamburgerActive && hamburger["is-active"]}`}
            type="button"
            onClick={() => setHamburgerActive(!hamburgerActive)}
          >
            <span className={hamburger.line}></span>
          </button>
        </div>
      </div>

      {/* Landing page */}
      
    </Layout>
  );
}
